"use strict";var g=Object.defineProperty;var R=Object.getOwnPropertyDescriptor;var P=Object.getOwnPropertyNames;var v=Object.prototype.hasOwnProperty;var b=(n,e)=>{for(var t in e)g(n,t,{get:e[t],enumerable:!0})},h=(n,e,t,i)=>{if(e&&typeof e=="object"||typeof e=="function")for(let o of P(e))!v.call(n,o)&&o!==t&&g(n,o,{get:()=>e[o],enumerable:!(i=R(e,o))||i.enumerable});return n};var M=n=>h(g({},"__esModule",{value:!0}),n);var j={};b(j,{handler:()=>$});module.exports=M(j);var m=require("@aws-sdk/client-sfn"),I=require("@aws-sdk/client-dynamodb"),d=require("@aws-sdk/lib-dynamodb"),T=require("@aws-sdk/client-eventbridge"),A=require("@aws-sdk/client-sns"),U=new m.SFNClient({}),N=d.DynamoDBDocumentClient.from(new I.DynamoDBClient({}),{marshallOptions:{removeUndefinedValues:!0}}),L=new T.EventBridgeClient({}),B=new A.SNSClient({}),S=process.env.TABLE_NAME,F=process.env.AUDIT_TABLE_NAME,_=process.env.PK_NAME||"pk",y=process.env.SK_NAME||"sk",C=process.env.NOTIFY_TOPIC_ARN,O=Number(process.env.MAX_PER_RUN||"25");function D(){return new Date().toISOString()}function J(n){return n?.name==="ConditionalCheckFailedException"}function K(n){let e=n?.name||"",t=String(n?.message||"");return e.includes("TaskTimedOut")||e.includes("InvalidToken")||e.includes("TaskDoesNotExist")||e.includes("ExecutionDoesNotExist")||t.toLowerCase().includes("invalid token")||t.toLowerCase().includes("task does not exist")||t.toLowerCase().includes("timed out")}async function X(n,e){try{await L.send(new T.PutEventsCommand({Entries:[{Source:"stylingadventures.closet",DetailType:n,Detail:JSON.stringify(e)}]}))}catch(t){console.warn("[expire] EventBridge put failed:",t)}}async function V(n,e){if(C)try{await B.send(new A.PublishCommand({TopicArn:C,Subject:"Closet approval expired",Message:`${n}

${JSON.stringify(e,null,2)}`}))}catch(t){console.warn("[expire] SNS publish failed:",t)}}async function E(n,e,t){let i=new Date;try{await N.send(new d.PutCommand({TableName:F,Item:{pk:`APPROVAL#${e}`,sk:`TS#${i.toISOString()}`,action:n,approvalId:e,at:i.toISOString(),detail:t}}))}catch(o){console.warn("[expire] audit write failed:",o)}}var $=async()=>{let n=Math.floor(Date.now()/1e3),e=D();console.log("[expire] start",{now:n,MAX_PER_RUN:O});let i=(await N.send(new d.ScanCommand({TableName:S,FilterExpression:"#s = :pending AND attribute_exists(taskToken) AND attribute_exists(taskTokenExpiresAt) AND taskTokenExpiresAt <= :now",ExpressionAttributeNames:{"#s":"status"},ExpressionAttributeValues:{":pending":"PENDING",":now":n},Limit:O}))).Items??[];console.log("[expire] candidates",{count:i.length});let o=0,k=0,w=0;for(let u of i){let a=u[_],c=u[y],s=String(u.id||a?.replace("ITEM#","")||""),f=u.taskToken;if(!a||!c||!s||!f){k++;continue}let l=D(),p="Approval token expired";try{await U.send(new m.SendTaskSuccessCommand({taskToken:f,output:JSON.stringify({decision:"REJECT",reason:p})}))}catch(r){K(r)?(console.log("[expire] token already closed/invalid; continuing",{approvalId:s}),await E("AUTO_EXPIRE_TOKEN_CLOSED",s,{pk:a,sk:c,decidedAt:l,reason:p,note:"Task token already closed/invalid"})):(console.error("[expire] SendTaskSuccess failed",{approvalId:s,err:r}),w++,await E("AUTO_EXPIRE_SFN_ERROR",s,{pk:a,sk:c,decidedAt:l,reason:p,error:String(r?.message||r)}))}try{await N.send(new d.UpdateCommand({TableName:S,Key:{[_]:a,[y]:c},ConditionExpression:"#s = :pending",UpdateExpression:`
            SET #s = :rejected,
                decidedAt = :t,
                updatedAt = :t
            REMOVE taskToken, taskTokenExpiresAt
          `,ExpressionAttributeNames:{"#s":"status"},ExpressionAttributeValues:{":pending":"PENDING",":rejected":"REJECTED",":t":l}}))}catch(r){if(J(r)){console.log("[expire] already decided",{approvalId:s}),k++;continue}console.error("[expire] update failed",{approvalId:s,err:r}),w++,await E("AUTO_EXPIRE_UPDATE_ERROR",s,{pk:a,sk:c,decidedAt:l,reason:p,error:String(r?.message||r)});continue}await E("AUTO_EXPIRE_REJECT",s,{pk:a,sk:c,decidedAt:l,reason:p}),await X("ClosetItemAutoExpired",{approvalId:s,pk:a,sk:c,decidedAt:l,reason:p}),await V(`Auto-rejected expired approval: ${s}`,{approvalId:s,pk:a,sk:c,decidedAt:l,reason:p}),o++}let x={ok:!0,startedAt:e,expired:o,skipped:k,errors:w,scanned:i.length};return console.log("[expire] done",x),x};0&&(module.exports={handler});
//# sourceMappingURL=index.js.map
