"use strict";var k=Object.defineProperty;var v=Object.getOwnPropertyDescriptor;var P=Object.getOwnPropertyNames;var b=Object.prototype.hasOwnProperty;var h=(t,e)=>{for(var n in e)k(t,n,{get:e[n],enumerable:!0})},M=(t,e,n,i)=>{if(e&&typeof e=="object"||typeof e=="function")for(let o of P(e))!b.call(t,o)&&o!==n&&k(t,o,{get:()=>e[o],enumerable:!(i=v(e,o))||i.enumerable});return t};var U=t=>M(k({},"__esModule",{value:!0}),t);var Y={};h(Y,{handler:()=>G});module.exports=U(Y);var m=require("@aws-sdk/client-sfn"),I=require("@aws-sdk/client-dynamodb"),d=require("@aws-sdk/lib-dynamodb"),A=require("@aws-sdk/client-eventbridge"),T=require("@aws-sdk/client-sns"),L=new m.SFNClient({}),N=d.DynamoDBDocumentClient.from(new I.DynamoDBClient({}),{marshallOptions:{removeUndefinedValues:!0}}),B=new A.EventBridgeClient({}),F=new T.SNSClient({}),x=process.env.TABLE_NAME,J=process.env.AUDIT_TABLE_NAME,y=process.env.PK_NAME||"pk",_=process.env.SK_NAME||"sk",C=process.env.NOTIFY_TOPIC_ARN,D=Number(process.env.MAX_PER_RUN||"25");function O(){return new Date().toISOString()}function X(t){return t?.name==="ConditionalCheckFailedException"}function K(t){let e=t?.name||"",n=String(t?.message||"");return e.includes("TaskTimedOut")||e.includes("InvalidToken")||e.includes("TaskDoesNotExist")||e.includes("ExecutionDoesNotExist")||n.toLowerCase().includes("invalid token")||n.toLowerCase().includes("task does not exist")||n.toLowerCase().includes("timed out")}function j(t,e,n={}){console.log(JSON.stringify({_aws:{Timestamp:Date.now(),CloudWatchMetrics:[{Namespace:"StylingAdventures/ClosetApprovals",Dimensions:[Object.keys(n)],Metrics:[{Name:t,Unit:"Seconds"}]}]},...n,[t]:e}))}async function V(t,e){try{await B.send(new A.PutEventsCommand({Entries:[{Source:"stylingadventures.closet",DetailType:t,Detail:JSON.stringify(e)}]}))}catch(n){console.warn("[expire] EventBridge put failed:",n)}}async function $(t,e){if(C)try{await F.send(new T.PublishCommand({TopicArn:C,Subject:"Closet approval expired",Message:`${t}

${JSON.stringify(e,null,2)}`}))}catch(n){console.warn("[expire] SNS publish failed:",n)}}async function E(t,e,n){let i=new Date;try{await N.send(new d.PutCommand({TableName:J,Item:{pk:`APPROVAL#${e}`,sk:`TS#${i.toISOString()}`,action:t,approvalId:e,at:i.toISOString(),detail:n}}))}catch(o){console.warn("[expire] audit write failed:",o)}}var G=async()=>{let t=Math.floor(Date.now()/1e3),e=O();console.log("[expire] start",{now:t,MAX_PER_RUN:D});let i=(await N.send(new d.ScanCommand({TableName:x,FilterExpression:"#s = :pending AND attribute_exists(taskToken) AND attribute_exists(taskTokenExpiresAt) AND taskTokenExpiresAt <= :now",ExpressionAttributeNames:{"#s":"status"},ExpressionAttributeValues:{":pending":"PENDING",":now":t},Limit:D}))).Items??[];console.log("[expire] candidates",{count:i.length});let o=0,g=0,w=0;for(let u of i){let a=u[y],c=u[_],s=String(u.id||a?.replace("ITEM#","")||""),f=u.taskToken;if(!a||!c||!s||!f){g++;continue}let l=O(),p="Approval token expired";try{await L.send(new m.SendTaskSuccessCommand({taskToken:f,output:JSON.stringify({decision:"REJECT",reason:p})}))}catch(r){K(r)?(console.log("[expire] token already closed/invalid; continuing",{approvalId:s}),await E("AUTO_EXPIRE_TOKEN_CLOSED",s,{pk:a,sk:c,decidedAt:l,reason:p,note:"Task token already closed/invalid"})):(console.error("[expire] SendTaskSuccess failed",{approvalId:s,err:r}),w++,await E("AUTO_EXPIRE_SFN_ERROR",s,{pk:a,sk:c,decidedAt:l,reason:p,error:String(r?.message||r)}))}try{await N.send(new d.UpdateCommand({TableName:x,Key:{[y]:a,[_]:c},ConditionExpression:"#s = :pending",UpdateExpression:`
            SET #s = :rejected,
                decidedAt = :t,
                updatedAt = :t
            REMOVE taskToken, taskTokenExpiresAt
          `,ExpressionAttributeNames:{"#s":"status"},ExpressionAttributeValues:{":pending":"PENDING",":rejected":"REJECTED",":t":l}}))}catch(r){if(X(r)){console.log("[expire] already decided",{approvalId:s}),g++;continue}console.error("[expire] update failed",{approvalId:s,err:r}),w++,await E("AUTO_EXPIRE_UPDATE_ERROR",s,{pk:a,sk:c,decidedAt:l,reason:p,error:String(r?.message||r)});continue}let R=Math.max(0,Math.floor((Date.now()-new Date(u.createdAt).getTime())/1e3));j("ApprovalLatencySeconds",R,{Outcome:"EXPIRED"}),await E("AUTO_EXPIRE_REJECT",s,{pk:a,sk:c,decidedAt:l,reason:p}),await V("ClosetItemAutoExpired",{approvalId:s,pk:a,sk:c,decidedAt:l,reason:p}),await $(`Auto-rejected expired approval: ${s}`,{approvalId:s,pk:a,sk:c,decidedAt:l,reason:p}),o++}let S={ok:!0,startedAt:e,expired:o,skipped:g,errors:w,scanned:i.length};return console.log("[expire] done",S),S};0&&(module.exports={handler});
//# sourceMappingURL=index.js.map
