"use strict";var L=Object.defineProperty;var I=Object.getOwnPropertyDescriptor;var S=Object.getOwnPropertyNames;var _=Object.prototype.hasOwnProperty;var h=(t,e)=>{for(var i in e)L(t,i,{get:e[i],enumerable:!0})},O=(t,e,i,n)=>{if(e&&typeof e=="object"||typeof e=="function")for(let s of S(e))!_.call(t,s)&&s!==i&&L(t,s,{get:()=>e[s],enumerable:!(n=I(e,s))||n.enumerable});return t};var M=t=>O(L({},"__esModule",{value:!0}),t);var X={};h(X,{handler:()=>z});module.exports=M(X);var U=require("@aws-sdk/client-dynamodb"),a=require("@aws-sdk/lib-dynamodb");var o=process.env.TABLE_NAME??process.env.APP_TABLE??process.env.TABLE??"";if(!o)throw new Error("Missing DynamoDB table env. Provide TABLE_NAME (or APP_TABLE / TABLE).");var c=a.DynamoDBDocumentClient.from(new U.DynamoDBClient({}),{marshallOptions:{removeUndefinedValues:!0}});function P(t){let e=t?.groups;return Array.isArray(e)&&e.includes("ADMIN")}function v(t,e){if(!e?.sub)throw new Error("Unauthenticated");if(!P(e)&&e.sub!==t)throw new Error("Forbidden")}function B(t){if(t==null)return null;if(typeof t=="string")try{return JSON.parse(t)}catch{return{raw:t}}return typeof t=="object"?t:{value:t}}function $(t){let e=1,i=100,n=t;for(;n>=i;)n-=i,e++,i+=50;return e}function N(t,e=12){return Math.max(0,t|0).toString().padStart(e,"0")}function F(t,e){if(!t||!e)return!1;let i=new Date(t),n=new Date(e);return i.getUTCFullYear()===n.getUTCFullYear()&&i.getUTCMonth()===n.getUTCMonth()&&i.getUTCDate()===n.getUTCDate()}function V(t,e){let i=new Date(t),n=new Date(e),s=new Date(Date.UTC(n.getUTCFullYear(),n.getUTCMonth(),n.getUTCDate()-1));return i.getUTCFullYear()===s.getUTCFullYear()&&i.getUTCMonth()===s.getUTCMonth()&&i.getUTCDate()===s.getUTCDate()}var z=async t=>{let{fieldName:e}=t.info,i=t.identity;if(e==="logGameEvent"){if(!i?.sub)throw new Error("Unauthenticated");let n=i.sub,s=new Date().toISOString(),E=t.arguments?.input??{},p=E.type||"UNKNOWN",l=B(E.metadata);if(p==="DAILY_LOGIN"){let D=await c.send(new a.GetCommand({TableName:o,Key:{pk:`USER#${n}`,sk:"PROFILE"},ProjectionExpression:"lastLoginAt, streakCount, xp, coins, badges, displayName, lastEventAt"})),g=D.Item?.lastLoginAt,w=typeof g=="string"?g:typeof g=="number"?new Date(g).toISOString():void 0,d=Number(D.Item?.streakCount??0),b=1,x=0;w&&F(w,s)?(b=0,x=0):w&&V(w,s)?d+=1:d=1,b=d>0?10+Math.min(5,d):0,x=d>0?1:0;let y=await c.send(new a.UpdateCommand({TableName:o,Key:{pk:`USER#${n}`,sk:"PROFILE"},UpdateExpression:`
          SET xp = if_not_exists(xp,:z) + :xi,
              coins = if_not_exists(coins,:z) + :ci,
              lastEventAt = :now,
              lastLoginAt = :now,
              streakCount = :st
        `.replace(/\s+/g," "),ExpressionAttributeValues:{":z":0,":xi":b,":ci":x,":now":s,":st":d},ReturnValues:"ALL_NEW"})),f=Number(y.Attributes?.xp??0),R=Number(y.Attributes?.coins??0),k=y.Attributes?.lastEventAt??s;return await c.send(new a.PutCommand({TableName:o,Item:{pk:`USER#${n}`,sk:"LEADER",gsi1pk:"LEADERBOARD#GLOBAL",gsi1sk:`XP#${N(f)}#${n}`,xp:f,coins:R,streakCount:d,updatedAt:s,type:"LEADER"}})),{success:!0,xp:f,coins:R,newXP:b,newCoins:x,lastEventAt:k}}let r=p==="LEVEL_CLEAR"?50:p==="SHARE"?5:p==="STYLE_IT"?Math.max(1,Math.round((l?.score??5)/5)):1,u=p==="LEVEL_CLEAR"?5:0,A=await c.send(new a.UpdateCommand({TableName:o,Key:{pk:`USER#${n}`,sk:"PROFILE"},UpdateExpression:`
        SET xp = if_not_exists(xp,:z) + :xi,
            coins = if_not_exists(coins,:z) + :ci,
            lastEventAt = :now
      `.replace(/\s+/g," "),ExpressionAttributeValues:{":z":0,":xi":r,":ci":u,":now":s},ReturnValues:"ALL_NEW"})),m=Number(A.Attributes?.xp??0),T=Number(A.Attributes?.coins??0),C=A.Attributes?.lastEventAt??s;return await c.send(new a.PutCommand({TableName:o,Item:{pk:`USER#${n}`,sk:"LEADER",gsi1pk:"LEADERBOARD#GLOBAL",gsi1sk:`XP#${N(m)}#${n}`,xp:m,coins:T,updatedAt:s,type:"LEADER"}})),await c.send(new a.PutCommand({TableName:o,Item:{pk:`USER#${n}`,sk:`EVENT#${Date.now()}`,type:"EVENT",evType:p,metadata:l,at:s},ConditionExpression:"attribute_not_exists(pk)"})).catch(()=>{}),{success:!0,xp:m,coins:T,newXP:r,newCoins:u,lastEventAt:C}}if(e==="awardCoins"){let{userId:n,coins:s,xp:E}=t.arguments.input;v(n,i);let p=Math.max(0,s|0),l=Math.max(0,(E??0)|0),r=await c.send(new a.UpdateCommand({TableName:o,Key:{pk:`USER#${n}`,sk:"PROFILE"},UpdateExpression:"SET coins = if_not_exists(coins,:z) + :c, xp = if_not_exists(xp,:z) + :x",ExpressionAttributeValues:{":z":0,":c":p,":x":l},ReturnValues:"ALL_NEW"})),u=Number(r.Attributes?.xp??0);return await c.send(new a.PutCommand({TableName:o,Item:{pk:`USER#${n}`,sk:"LEADER",gsi1pk:"LEADERBOARD#GLOBAL",gsi1sk:`XP#${N(u)}#${n}`,xp:u,coins:Number(r.Attributes?.coins??0),updatedAt:new Date().toISOString(),type:"LEADER"}})),{userId:n,displayName:r.Attributes?.displayName||null,level:$(u),xp:u,coins:Number(r.Attributes?.coins??0),badges:Array.isArray(r.Attributes?.badges)?r.Attributes.badges:[],lastEventAt:r.Attributes?.lastEventAt??null}}if(e==="topXP"){let n=Math.max(1,Math.min(100,Number(t.arguments?.limit??10))),E=(await c.send(new a.QueryCommand({TableName:o,IndexName:"gsi1",KeyConditionExpression:"gsi1pk = :p",ExpressionAttributeValues:{":p":"LEADERBOARD#GLOBAL"},ScanIndexForward:!1,Limit:n}))).Items??[];return await Promise.all(E.map(async(l,r)=>{let u=l.pk.replace("USER#",""),A;try{A=(await c.send(new a.GetCommand({TableName:o,Key:{pk:`USER#${u}`,sk:"PROFILE"},ProjectionExpression:"displayName"}))).Item?.displayName}catch{}return{userId:u,displayName:A,xp:Number(l.xp??0),coins:Number(l.coins??0),rank:r+1}}))}throw new Error(`Unknown field ${e}`)};0&&(module.exports={handler});
