"use strict";var L=Object.defineProperty;var U=Object.getOwnPropertyDescriptor;var k=Object.getOwnPropertyNames;var C=Object.prototype.hasOwnProperty;var I=(t,n)=>{for(var i in n)L(t,i,{get:n[i],enumerable:!0})},S=(t,n,i,e)=>{if(n&&typeof n=="object"||typeof n=="function")for(let s of k(n))!C.call(t,s)&&s!==i&&L(t,s,{get:()=>n[s],enumerable:!(e=U(n,s))||e.enumerable});return t};var _=t=>S(L({},"__esModule",{value:!0}),t);var $={};I($,{handler:()=>P});module.exports=_($);var R=require("@aws-sdk/client-dynamodb"),a=require("@aws-sdk/lib-dynamodb");var r=process.env.TABLE_NAME??process.env.APP_TABLE??process.env.TABLE??"";if(!r)throw new Error("Missing DynamoDB table env. Provide TABLE_NAME (or APP_TABLE / TABLE).");var p=a.DynamoDBDocumentClient.from(new R.DynamoDBClient({}),{marshallOptions:{removeUndefinedValues:!0}});function h(t){let n=t?.groups;return Array.isArray(n)&&n.includes("ADMIN")}function v(t,n){if(!n?.sub)throw new Error("Unauthenticated");if(!h(n)&&n.sub!==t)throw new Error("Forbidden")}function O(t){if(t==null)return null;if(typeof t=="string")try{return JSON.parse(t)}catch{return{raw:t}}return typeof t=="object"?t:{value:t}}function f(t){let n=1,i=100,e=t;for(;e>=i;)e-=i,n++,i+=50;return n}function T(t,n=12){return Math.max(0,t|0).toString().padStart(n,"0")}function M(t,n){if(!t||!n)return!1;let i=new Date(t),e=new Date(n);return i.getUTCFullYear()===e.getUTCFullYear()&&i.getUTCMonth()===e.getUTCMonth()&&i.getUTCDate()===e.getUTCDate()}function B(t,n){let i=new Date(t),e=new Date(n),s=new Date(Date.UTC(e.getUTCFullYear(),e.getUTCMonth(),e.getUTCDate()-1));return i.getUTCFullYear()===s.getUTCFullYear()&&i.getUTCMonth()===s.getUTCMonth()&&i.getUTCDate()===s.getUTCDate()}var P=async t=>{let{fieldName:n}=t.info,i=t.identity;if(n==="logGameEvent"){if(!i?.sub)throw new Error("Unauthenticated");let e=i.sub,s=new Date().toISOString(),m=t.arguments?.input??{},l=m.type||"UNKNOWN",d=O(m.metadata);if(l==="DAILY_LOGIN"){let D=await p.send(new a.GetCommand({TableName:r,Key:{pk:`USER#${e}`,sk:"PROFILE"},ProjectionExpression:"lastLoginAt, streakCount, xp, coins, badges, displayName, lastEventAt"})),b=D.Item?.lastLoginAt,y=typeof b=="string"?b:typeof b=="number"?new Date(b).toISOString():void 0,A=Number(D.Item?.streakCount??0),w=1,N=0;y&&M(y,s)?(w=0,N=0):y&&B(y,s)?A+=1:A=1,w=A>0?10+Math.min(5,A):0,N=A>0?1:0;let E=await p.send(new a.UpdateCommand({TableName:r,Key:{pk:`USER#${e}`,sk:"PROFILE"},UpdateExpression:`
          SET xp = if_not_exists(xp,:z) + :xi,
              coins = if_not_exists(coins,:z) + :ci,
              lastEventAt = :now,
              lastLoginAt = :now,
              streakCount = :st
        `.replace(/\s+/g," "),ExpressionAttributeValues:{":z":0,":xi":w,":ci":N,":now":s,":st":A},ReturnValues:"ALL_NEW"})),x=Number(E.Attributes?.xp??0);return await p.send(new a.PutCommand({TableName:r,Item:{pk:`USER#${e}`,sk:"LEADER",gsi1pk:"LEADERBOARD#GLOBAL",gsi1sk:`XP#${T(x)}#${e}`,xp:x,coins:Number(E.Attributes?.coins??0),streakCount:A,updatedAt:s,type:"LEADER"}})),{userId:e,displayName:E.Attributes?.displayName||null,level:f(x),xp:x,coins:Number(E.Attributes?.coins??0),badges:Array.isArray(E.Attributes?.badges)?E.Attributes.badges:[],lastEventAt:E.Attributes?.lastEventAt??s,lastLoginAt:s,streakCount:A}}let o=l==="LEVEL_CLEAR"?50:l==="SHARE"?5:l==="STYLE_IT"?Math.max(1,Math.round((d?.score??5)/5)):1,c=l==="LEVEL_CLEAR"?5:0,u=await p.send(new a.UpdateCommand({TableName:r,Key:{pk:`USER#${e}`,sk:"PROFILE"},UpdateExpression:`
        SET xp = if_not_exists(xp,:z) + :xi,
            coins = if_not_exists(coins,:z) + :ci,
            lastEventAt = :now
      `.replace(/\s+/g," "),ExpressionAttributeValues:{":z":0,":xi":o,":ci":c,":now":s},ReturnValues:"ALL_NEW"})),g=Number(u.Attributes?.xp??0);return await p.send(new a.PutCommand({TableName:r,Item:{pk:`USER#${e}`,sk:"LEADER",gsi1pk:"LEADERBOARD#GLOBAL",gsi1sk:`XP#${T(g)}#${e}`,xp:g,coins:Number(u.Attributes?.coins??0),updatedAt:s,type:"LEADER"}})),await p.send(new a.PutCommand({TableName:r,Item:{pk:`USER#${e}`,sk:`EVENT#${Date.now()}`,type:"EVENT",evType:l,metadata:d,at:s},ConditionExpression:"attribute_not_exists(pk)"})).catch(()=>{}),{userId:e,displayName:u.Attributes?.displayName||null,level:f(g),xp:g,coins:Number(u.Attributes?.coins??0),badges:Array.isArray(u.Attributes?.badges)?u.Attributes.badges:[],lastEventAt:u.Attributes?.lastEventAt??s}}if(n==="awardCoins"){let{userId:e,coins:s,xp:m}=t.arguments.input;v(e,i);let l=Math.max(0,s|0),d=Math.max(0,(m??0)|0),o=await p.send(new a.UpdateCommand({TableName:r,Key:{pk:`USER#${e}`,sk:"PROFILE"},UpdateExpression:"SET coins = if_not_exists(coins,:z) + :c, xp = if_not_exists(xp,:z) + :x",ExpressionAttributeValues:{":z":0,":c":l,":x":d},ReturnValues:"ALL_NEW"})),c=Number(o.Attributes?.xp??0);return await p.send(new a.PutCommand({TableName:r,Item:{pk:`USER#${e}`,sk:"LEADER",gsi1pk:"LEADERBOARD#GLOBAL",gsi1sk:`XP#${T(c)}#${e}`,xp:c,coins:Number(o.Attributes?.coins??0),updatedAt:new Date().toISOString(),type:"LEADER"}})),{userId:e,displayName:o.Attributes?.displayName||null,level:f(c),xp:c,coins:Number(o.Attributes?.coins??0),badges:Array.isArray(o.Attributes?.badges)?o.Attributes.badges:[],lastEventAt:o.Attributes?.lastEventAt??null}}if(n==="topXP"){let e=Math.max(1,Math.min(100,Number(t.arguments?.limit??10))),m=(await p.send(new a.QueryCommand({TableName:r,IndexName:"gsi1",KeyConditionExpression:"gsi1pk = :p",ExpressionAttributeValues:{":p":"LEADERBOARD#GLOBAL"},ScanIndexForward:!1,Limit:e}))).Items??[];return await Promise.all(m.map(async(d,o)=>{let c=d.pk.replace("USER#",""),u;try{u=(await p.send(new a.GetCommand({TableName:r,Key:{pk:`USER#${c}`,sk:"PROFILE"},ProjectionExpression:"displayName"}))).Item?.displayName}catch{}return{userId:c,displayName:u,xp:Number(d.xp??0),coins:Number(d.coins??0),rank:o+1}}))}throw new Error(`Unknown field ${n}`)};0&&(module.exports={handler});
