"use strict";var y=Object.defineProperty;var k=Object.getOwnPropertyDescriptor;var M=Object.getOwnPropertyNames;var O=Object.prototype.hasOwnProperty;var _=(t,e)=>{for(var s in e)y(t,s,{get:e[s],enumerable:!0})},B=(t,e,s,n)=>{if(e&&typeof e=="object"||typeof e=="function")for(let i of M(e))!O.call(t,i)&&i!==s&&y(t,i,{get:()=>e[i],enumerable:!(n=k(e,i))||n.enumerable});return t};var h=t=>B(y({},"__esModule",{value:!0}),t);var G={};_(G,{handler:()=>Y});module.exports=h(G);var D=require("@aws-sdk/client-dynamodb"),r=require("@aws-sdk/lib-dynamodb");var u=process.env.TABLE_NAME??process.env.APP_TABLE??process.env.TABLE??"";if(!u)throw new Error("Missing DynamoDB table env. Provide TABLE_NAME (or APP_TABLE / TABLE).");var c=r.DynamoDBDocumentClient.from(new D.DynamoDBClient({}),{marshallOptions:{removeUndefinedValues:!0}});function v(t){let e=t?.groups;return Array.isArray(e)?e.includes("ADMIN")||e.includes("PRIME"):!1}function P(t,e){if(!e?.sub)throw new Error("Unauthenticated");if(!v(e)&&e.sub!==t)throw new Error("Forbidden")}function $(t){let e=t?.claims||{},s=e.tier??e["custom:tier"];if(s&&["FREE","BESTIE","CREATOR","COLLAB","ADMIN","PRIME"].includes(s))return s;let i=e["cognito:groups"],o=Array.isArray(i)?i:String(i||"").split(",").map(a=>a.trim()).filter(Boolean);return o.includes("ADMIN")?"ADMIN":o.includes("PRIME")?"PRIME":o.includes("CREATOR")?"CREATOR":o.includes("COLLAB")?"COLLAB":o.includes("BESTIE")?"BESTIE":"FREE"}function F(t){if(t==null)return null;if(typeof t=="string")try{return JSON.parse(t)}catch{return{raw:t}}return typeof t=="object"?t:{value:t}}function V(t){let e=1,s=100,n=t|0;for(;n>=s;)n-=s,e++,s+=50;return e}function R(t,e=12){return Math.max(0,t|0).toString().padStart(e,"0")}function z(t,e){if(!t||!e)return!1;let s=new Date(t),n=new Date(e);return s.getUTCFullYear()===n.getUTCFullYear()&&s.getUTCMonth()===n.getUTCMonth()&&s.getUTCDate()===n.getUTCDate()}function X(t,e){let s=new Date(t),n=new Date(e),i=new Date(Date.UTC(n.getUTCFullYear(),n.getUTCMonth(),n.getUTCDate()-1));return s.getUTCFullYear()===i.getUTCFullYear()&&s.getUTCMonth()===i.getUTCMonth()&&s.getUTCDate()===i.getUTCDate()}var Y=async t=>{let{fieldName:e}=t.info,s=t.identity;if(e==="logGameEvent"){if(!s?.sub)throw new Error("Unauthenticated");let n=s.sub,i=new Date().toISOString(),o=t.arguments?.input??{},a=o.type||"UNKNOWN",g=F(o.metadata);if($(s)==="FREE")return{success:!0,xp:0,coins:0,newXP:0,newCoins:0,lastEventAt:i};if(a==="DAILY_LOGIN"){let C=await c.send(new r.GetCommand({TableName:u,Key:{pk:`USER#${n}`,sk:"PROFILE"},ProjectionExpression:"lastLoginAt, streakCount, xp, coins, badges, displayName, lastEventAt"})),m=C.Item?.lastLoginAt,f=typeof m=="string"?m:typeof m=="number"?new Date(m).toISOString():void 0,l=Number(C.Item?.streakCount??0),w=1,T=0;f&&z(f,i)?(w=0,T=0):f&&X(f,i)?l+=1:l=1,w=l>0?10+Math.min(5,l):0,T=l>0?1:0;let b=await c.send(new r.UpdateCommand({TableName:u,Key:{pk:`USER#${n}`,sk:"PROFILE"},UpdateExpression:`
            SET xp = if_not_exists(xp,:z) + :xi,
                coins = if_not_exists(coins,:z) + :ci,
                lastEventAt = :now,
                lastLoginAt = :now,
                streakCount = :st
          `.replace(/\s+/g," "),ExpressionAttributeValues:{":z":0,":xi":w,":ci":T,":now":i,":st":l},ReturnValues:"ALL_NEW"})),x=Number(b.Attributes?.xp??0),I=Number(b.Attributes?.coins??0),S=b.Attributes?.lastEventAt??i;return await c.send(new r.PutCommand({TableName:u,Item:{pk:`USER#${n}`,sk:"LEADER",gsi1pk:"LEADERBOARD#GLOBAL",gsi1sk:`XP#${R(x)}#${n}`,xp:x,coins:I,streakCount:l,updatedAt:i,type:"LEADER"}})),{success:!0,xp:x,coins:I,newXP:w,newCoins:T,lastEventAt:S}}let p=a==="LEVEL_CLEAR"?50:a==="SHARE"?5:a==="STYLE_IT"?Math.max(1,Math.round((g?.score??5)/5)):1,A=a==="LEVEL_CLEAR"?5:0,d=await c.send(new r.UpdateCommand({TableName:u,Key:{pk:`USER#${n}`,sk:"PROFILE"},UpdateExpression:`
          SET xp = if_not_exists(xp,:z) + :xi,
              coins = if_not_exists(coins,:z) + :ci,
              lastEventAt = :now
        `.replace(/\s+/g," "),ExpressionAttributeValues:{":z":0,":xi":p,":ci":A,":now":i},ReturnValues:"ALL_NEW"})),L=Number(d.Attributes?.xp??0),N=Number(d.Attributes?.coins??0),U=d.Attributes?.lastEventAt??i;return await c.send(new r.PutCommand({TableName:u,Item:{pk:`USER#${n}`,sk:"LEADER",gsi1pk:"LEADERBOARD#GLOBAL",gsi1sk:`XP#${R(L)}#${n}`,xp:L,coins:N,updatedAt:i,type:"LEADER"}})),await c.send(new r.PutCommand({TableName:u,Item:{pk:`USER#${n}`,sk:`EVENT#${Date.now()}`,type:"EVENT",evType:a,metadata:g,at:i},ConditionExpression:"attribute_not_exists(pk)"})).catch(()=>{}),{success:!0,xp:L,coins:N,newXP:p,newCoins:A,lastEventAt:U}}if(e==="awardCoins"){let{userId:n,coins:i,xp:o}=t.arguments.input;P(n,s);let a=Math.max(0,i|0),g=Math.max(0,(o??0)|0),E=await c.send(new r.UpdateCommand({TableName:u,Key:{pk:`USER#${n}`,sk:"PROFILE"},UpdateExpression:"SET coins = if_not_exists(coins,:z) + :c, xp = if_not_exists(xp,:z) + :x",ExpressionAttributeValues:{":z":0,":c":a,":x":g},ReturnValues:"ALL_NEW"})),p=Number(E.Attributes?.xp??0),A=Number(E.Attributes?.coins??0),d=E.Attributes?.lastEventAt??null;return await c.send(new r.PutCommand({TableName:u,Item:{pk:`USER#${n}`,sk:"LEADER",gsi1pk:"LEADERBOARD#GLOBAL",gsi1sk:`XP#${R(p)}#${n}`,xp:p,coins:A,updatedAt:new Date().toISOString(),type:"LEADER"}})),{userId:n,displayName:E.Attributes?.displayName||null,level:V(p),xp:p,coins:A,badges:Array.isArray(E.Attributes?.badges)?E.Attributes.badges:[],lastEventAt:d}}throw new Error(`Unknown field ${e}`)};0&&(module.exports={handler});
