"use strict";var y=Object.defineProperty;var k=Object.getOwnPropertyDescriptor;var I=Object.getOwnPropertyNames;var _=Object.prototype.hasOwnProperty;var h=(t,e)=>{for(var s in e)y(t,s,{get:e[s],enumerable:!0})},v=(t,e,s,n)=>{if(e&&typeof e=="object"||typeof e=="function")for(let i of I(e))!_.call(t,i)&&i!==s&&y(t,i,{get:()=>e[i],enumerable:!(n=k(e,i))||n.enumerable});return t};var M=t=>v(y({},"__esModule",{value:!0}),t);var Y={};h(Y,{handler:()=>z});module.exports=M(Y);var C=require("@aws-sdk/client-dynamodb"),o=require("@aws-sdk/lib-dynamodb");var r=process.env.TABLE_NAME??process.env.APP_TABLE??process.env.TABLE??"";if(!r)throw new Error("Missing DynamoDB table env. Provide TABLE_NAME (or APP_TABLE / TABLE).");var c=o.DynamoDBDocumentClient.from(new C.DynamoDBClient({}),{marshallOptions:{removeUndefinedValues:!0}});function O(t){let e=t?.groups;return Array.isArray(e)&&e.includes("ADMIN")}function B(t,e){if(!e?.sub)throw new Error("Unauthenticated");if(!O(e)&&e.sub!==t)throw new Error("Forbidden")}function P(t){if(t==null)return null;if(typeof t=="string")try{return JSON.parse(t)}catch{return{raw:t}}return typeof t=="object"?t:{value:t}}function $(t){let e=1,s=100,n=t|0;for(;n>=s;)n-=s,e++,s+=50;return e}function N(t,e=12){return Math.max(0,t|0).toString().padStart(e,"0")}function F(t,e){if(!t||!e)return!1;let s=new Date(t),n=new Date(e);return s.getUTCFullYear()===n.getUTCFullYear()&&s.getUTCMonth()===n.getUTCMonth()&&s.getUTCDate()===n.getUTCDate()}function V(t,e){let s=new Date(t),n=new Date(e),i=new Date(Date.UTC(n.getUTCFullYear(),n.getUTCMonth(),n.getUTCDate()-1));return s.getUTCFullYear()===i.getUTCFullYear()&&s.getUTCMonth()===i.getUTCMonth()&&s.getUTCDate()===i.getUTCDate()}var z=async t=>{let{fieldName:e}=t.info,s=t.identity;if(e==="logGameEvent"){if(!s?.sub)throw new Error("Unauthenticated");let n=s.sub,i=new Date().toISOString(),d=t.arguments?.input??{},u=d.type||"UNKNOWN",g=P(d.metadata);if(u==="DAILY_LOGIN"){let D=await c.send(new o.GetCommand({TableName:r,Key:{pk:`USER#${n}`,sk:"PROFILE"},ProjectionExpression:"lastLoginAt, streakCount, xp, coins, badges, displayName, lastEventAt"})),m=D.Item?.lastLoginAt,w=typeof m=="string"?m:typeof m=="number"?new Date(m).toISOString():void 0,l=Number(D.Item?.streakCount??0),b=1,x=0;w&&F(w,i)?(b=0,x=0):w&&V(w,i)?l+=1:l=1,b=l>0?10+Math.min(5,l):0,x=l>0?1:0;let f=await c.send(new o.UpdateCommand({TableName:r,Key:{pk:`USER#${n}`,sk:"PROFILE"},UpdateExpression:`
          SET xp = if_not_exists(xp,:z) + :xi,
              coins = if_not_exists(coins,:z) + :ci,
              lastEventAt = :now,
              lastLoginAt = :now,
              streakCount = :st
        `.replace(/\s+/g," "),ExpressionAttributeValues:{":z":0,":xi":b,":ci":x,":now":i,":st":l},ReturnValues:"ALL_NEW"})),L=Number(f.Attributes?.xp??0),U=Number(f.Attributes?.coins??0),S=f.Attributes?.lastEventAt??i;return await c.send(new o.PutCommand({TableName:r,Item:{pk:`USER#${n}`,sk:"LEADER",gsi1pk:"LEADERBOARD#GLOBAL",gsi1sk:`XP#${N(L)}#${n}`,xp:L,coins:U,streakCount:l,updatedAt:i,type:"LEADER"}})),{success:!0,xp:L,coins:U,newXP:b,newCoins:x,lastEventAt:S}}let a=u==="LEVEL_CLEAR"?50:u==="SHARE"?5:u==="STYLE_IT"?Math.max(1,Math.round((g?.score??5)/5)):1,p=u==="LEVEL_CLEAR"?5:0,E=await c.send(new o.UpdateCommand({TableName:r,Key:{pk:`USER#${n}`,sk:"PROFILE"},UpdateExpression:`
        SET xp = if_not_exists(xp,:z) + :xi,
            coins = if_not_exists(coins,:z) + :ci,
            lastEventAt = :now
      `.replace(/\s+/g," "),ExpressionAttributeValues:{":z":0,":xi":a,":ci":p,":now":i},ReturnValues:"ALL_NEW"})),A=Number(E.Attributes?.xp??0),T=Number(E.Attributes?.coins??0),R=E.Attributes?.lastEventAt??i;return await c.send(new o.PutCommand({TableName:r,Item:{pk:`USER#${n}`,sk:"LEADER",gsi1pk:"LEADERBOARD#GLOBAL",gsi1sk:`XP#${N(A)}#${n}`,xp:A,coins:T,updatedAt:i,type:"LEADER"}})),await c.send(new o.PutCommand({TableName:r,Item:{pk:`USER#${n}`,sk:`EVENT#${Date.now()}`,type:"EVENT",evType:u,metadata:g,at:i},ConditionExpression:"attribute_not_exists(pk)"})).catch(()=>{}),{success:!0,xp:A,coins:T,newXP:a,newCoins:p,lastEventAt:R}}if(e==="awardCoins"){let{userId:n,coins:i,xp:d}=t.arguments.input;B(n,s);let u=Math.max(0,i|0),g=Math.max(0,(d??0)|0),a=await c.send(new o.UpdateCommand({TableName:r,Key:{pk:`USER#${n}`,sk:"PROFILE"},UpdateExpression:"SET coins = if_not_exists(coins,:z) + :c, xp = if_not_exists(xp,:z) + :x",ExpressionAttributeValues:{":z":0,":c":u,":x":g},ReturnValues:"ALL_NEW"})),p=Number(a.Attributes?.xp??0),E=Number(a.Attributes?.coins??0),A=a.Attributes?.lastEventAt??null;return await c.send(new o.PutCommand({TableName:r,Item:{pk:`USER#${n}`,sk:"LEADER",gsi1pk:"LEADERBOARD#GLOBAL",gsi1sk:`XP#${N(p)}#${n}`,xp:p,coins:E,updatedAt:new Date().toISOString(),type:"LEADER"}})),{userId:n,displayName:a.Attributes?.displayName||null,level:$(p),xp:p,coins:E,badges:Array.isArray(a.Attributes?.badges)?a.Attributes.badges:[],lastEventAt:A}}throw new Error(`Unknown field ${e}`)};0&&(module.exports={handler});
