"use strict";var u=Object.defineProperty;var p=Object.getOwnPropertyDescriptor;var f=Object.getOwnPropertyNames;var h=Object.prototype.hasOwnProperty;var A=(t,e)=>{for(var o in e)u(t,o,{get:e[o],enumerable:!0})},R=(t,e,o,n)=>{if(e&&typeof e=="object"||typeof e=="function")for(let r of f(e))!h.call(t,r)&&r!==o&&u(t,r,{get:()=>e[r],enumerable:!(n=p(e,r))||n.enumerable});return t};var O=t=>R(u({},"__esModule",{value:!0}),t);var S={};A(S,{handler:()=>I});module.exports=O(S);var c=require("@aws-sdk/client-bedrock-runtime"),N=process.env.STORY_SCHEDULER_ARN||"",g=process.env.BEDROCK_MODEL_ID||"anthropic.claude-3-5-sonnet-20240620-v1:0",d=process.env.BEDROCK_REGION||process.env.AWS_REGION;function y(t){let e=t?.claims||{},o=e["custom:tier"]||e.tier,n=e["cognito:groups"],r=Array.isArray(n)?n:String(n||"").split(",").map(s=>s.trim()).filter(Boolean);return r.includes("ADMIN")?"ADMIN":r.includes("COLLAB")?"COLLAB":r.includes("PRIME")?"PRIME":r.includes("CREATOR")?"CREATOR":r.includes("BESTIE")?"BESTIE":o&&["FREE","BESTIE","CREATOR","COLLAB","ADMIN","PRIME"].includes(o)?o:"FREE"}function C(t){let e=y(t);if(!["CREATOR","COLLAB","ADMIN","PRIME"].includes(e))throw new Error("Creator tier required");return e}var l=d&&g?new c.BedrockRuntimeClient({region:d}):null;async function T(t,e){if(!l)throw new Error("Bedrock not configured");let n={anthropic_version:"bedrock-2023-05-31",max_tokens:256,temperature:.7,messages:[{role:"user",content:[{type:"text",text:e==="CAPTION"?`You are helping a fashion content creator write short social captions.
Return a JSON array of 2-4 caption strings only. Each caption should be under 120 characters and feel natural on TikTok/IG. Base them on this context:

"${t}"`:e==="HASHTAGS"?`You are helping a fashion creator pick hashtags.
Return a JSON array of 2-3 strings. Each string should be a space-separated list of 4-7 hashtags. Base them on this context:

"${t}"`:`You are helping a fashion content creator with planning and hooks.
Return a JSON array of 2-4 short suggestion strings. Each suggestion should be under 160 characters. Base them on this context:

"${t}"`}]}]},r=await l.send(new c.InvokeModelCommand({modelId:g,contentType:"application/json",accept:"application/json",body:Buffer.from(JSON.stringify(n))})),s=JSON.parse(new TextDecoder("utf-8").decode(r.body)),i=s?.output?.messages?.[0]?.content?.[0]?.text??s?.content?.[0]?.text??"";try{let a=JSON.parse(i);if(Array.isArray(a))return a.map(E=>String(E))}catch{}return i.split(/\r?\n/).map(a=>a.trim()).filter(Boolean)}var I=async t=>{console.log("CreatorAiFn event",JSON.stringify(t));let e=t.info?.fieldName,o=t.identity;switch(C(o),e){case"creatorAiSuggest":{let{text:n="",kind:r="OTHER"}=t.arguments||{},s=r==="CAPTION"||r==="HASHTAGS"?r:"OTHER";try{let i=await T(n,s);if(i.length)return{suggestions:i}}catch(i){console.error("[CreatorAiFn] Bedrock error",i)}return s==="CAPTION"?{suggestions:[`\u2728 ${n||"New look"} \u2014 styled by you.`,`Outfit check: ${n||"today's fit"} \u2728`]}:s==="HASHTAGS"?{suggestions:["#stylelala #outfitideas #creatorstudio"]}:{suggestions:["Try a short, punchy hook plus 3 strong hashtags."]}}default:throw new Error(`Unsupported field in CreatorAiFn: ${e}`)}};0&&(module.exports={handler});
//# sourceMappingURL=index.js.map
