"use strict";var f=Object.defineProperty;var h=Object.getOwnPropertyDescriptor;var R=Object.getOwnPropertyNames;var v=Object.prototype.hasOwnProperty;var M=(e,t)=>{for(var n in t)f(e,n,{get:t[n],enumerable:!0})},_=(e,t,n,s)=>{if(t&&typeof t=="object"||typeof t=="function")for(let o of R(t))!v.call(e,o)&&o!==n&&f(e,o,{get:()=>t[o],enumerable:!(s=h(t,o))||s.enumerable});return e};var b=e=>_(f({},"__esModule",{value:!0}),e);var G={};M(G,{handler:()=>q});module.exports=b(G);var p=require("@aws-sdk/client-sfn"),D=require("@aws-sdk/client-dynamodb"),i=require("@aws-sdk/lib-dynamodb"),m=require("@aws-sdk/client-eventbridge"),E=require("@aws-sdk/client-sns"),x=new p.SFNClient({}),y=i.DynamoDBDocumentClient.from(new D.DynamoDBClient({}),{marshallOptions:{removeUndefinedValues:!0}}),V=new m.EventBridgeClient({}),J=new E.SNSClient({}),w=process.env.TABLE_NAME,U=process.env.AUDIT_TABLE_NAME,C=process.env.PK_NAME||"pk",k=process.env.SK_NAME||"sk",P=process.env.NOTIFY_TOPIC_ARN;function a(e,t){return{statusCode:e,headers:{"content-type":"application/json","access-control-allow-origin":"*","access-control-allow-methods":"OPTIONS,POST","access-control-allow-headers":"*"},body:JSON.stringify(t)}}function B(e){let t=e?.requestContext?.http?.method;if(t)return String(t).toUpperCase();let n=e?.requestContext?.httpMethod;if(n)return String(n).toUpperCase();let s=e?.httpMethod;if(s)return String(s).toUpperCase()}function L(e){if(typeof e!="string")return e??{};try{return JSON.parse(e)}catch{return{}}}function I(e){return e?.name==="ConditionalCheckFailedException"}function F(e){let t=String(e?.name||""),n=String(e?.message||"").toLowerCase();return t.includes("TaskTimedOut")||t.includes("InvalidToken")||t.includes("TaskDoesNotExist")||t.includes("ExecutionDoesNotExist")||n.includes("invalid token")||n.includes("task does not exist")||n.includes("timed out")}function K(e,t,n={}){console.log(JSON.stringify({_aws:{Timestamp:Date.now(),CloudWatchMetrics:[{Namespace:"StylingAdventures/ClosetApprovals",Dimensions:[Object.keys(n)],Metrics:[{Name:e,Unit:"Seconds"}]}]},...n,[e]:t}))}async function $(e,t){try{await V.send(new m.PutEventsCommand({Entries:[{Source:"stylingadventures.closet",DetailType:e,Detail:JSON.stringify(t)}]}))}catch(n){console.warn("[approve] EventBridge emit failed:",n)}}async function j(e,t,n){if(P)try{await J.send(new E.PublishCommand({TopicArn:P,Subject:e,Message:`${t}

${JSON.stringify(n,null,2)}`}))}catch(s){console.warn("[approve] SNS publish failed:",s)}}async function g(e,t,n){let s=new Date;try{await y.send(new i.PutCommand({TableName:U,Item:{pk:`APPROVAL#${t}`,sk:`TS#${s.toISOString()}`,action:e,approvalId:t,at:s.toISOString(),detail:n}}))}catch(o){console.warn("[approve] audit write failed:",o)}}var q=async e=>{if(B(e)==="OPTIONS")return a(200,{ok:!0});try{let n=L(e?.body),s=n?.approvalId,o=n?.decision,c=n?.reason??(o==="APPROVE"?"Approved by admin":"Rejected by admin");if(!s||!o)return a(400,{message:"Missing approvalId or decision"});if(o!=="APPROVE"&&o!=="REJECT")return a(400,{message:"decision must be APPROVE or REJECT"});let A=`ITEM#${s}`,S="META",{Item:d}=await y.send(new i.GetCommand({TableName:w,Key:{[C]:A,[k]:S},ConsistentRead:!0}));if(!d)return a(404,{message:"Item not found"});if(d.status&&d.status!=="PENDING")return a(200,{ok:!0,idempotent:!0,approvalId:s,status:d.status});let N=d.taskToken;if(!N)return a(409,{ok:!1,message:"Missing taskToken (NotifyAdminFn not run yet)",approvalId:s});let T=d.approvalRequestedAt;if(T){let r=Math.max(0,Math.floor((Date.now()-new Date(T).getTime())/1e3));K("ApprovalLatencySeconds",r,{Outcome:o==="APPROVE"?"APPROVED":"REJECTED"})}let u=new Date().toISOString(),O=o==="APPROVE"?"APPROVED":"REJECTED";try{await y.send(new i.UpdateCommand({TableName:w,Key:{[C]:A,[k]:S},ConditionExpression:"#s = :pending",UpdateExpression:`
            SET #s = :s,
                decision = :d,
                decisionReason = :r,
                decidedAt = :t,
                updatedAt = :t
            REMOVE taskToken, taskTokenExpiresAt
          `,ExpressionAttributeNames:{"#s":"status"},ExpressionAttributeValues:{":pending":"PENDING",":s":O,":d":o,":r":c,":t":u}}))}catch(r){if(I(r))return a(200,{ok:!0,idempotent:!0,approvalId:s});throw r}let l=!0;try{await x.send(new p.SendTaskSuccessCommand({taskToken:N,output:JSON.stringify({decision:o,reason:c})}))}catch(r){l=!1,F(r)?(console.warn("[approve] task token already closed/invalid; continuing",{approvalId:s,err:r?.name||r}),await g("ADMIN_DECISION_TOKEN_CLOSED",s,{approvalId:s,decision:o,reason:c,at:u,error:String(r?.message||r)})):(console.error("[approve] SendTaskSuccess failed",r),await g("ADMIN_DECISION_SFN_ERROR",s,{approvalId:s,decision:o,reason:c,at:u,error:String(r?.message||r)}))}return await g(o==="APPROVE"?"ADMIN_APPROVE":"ADMIN_REJECT",s,{approvalId:s,decision:o,reason:c,decidedAt:u,sfnOk:l}),await $(o==="APPROVE"?"ClosetItemApproved":"ClosetItemRejected",{approvalId:s,decision:o,reason:c,decidedAt:u,sfnOk:l}),await j("Closet approval decision",`${o} for ${s}`,{approvalId:s,decision:o,reason:c,decidedAt:u,sfnOk:l}),a(200,{ok:!0,approvalId:s,status:O,sfnOk:l})}catch(n){return console.error("[approve] error:",n),I(n)?a(200,{ok:!0,idempotent:!0}):a(500,{message:"Internal error"})}};0&&(module.exports={handler});
//# sourceMappingURL=index.js.map
