"use strict";var E=Object.defineProperty;var O=Object.getOwnPropertyDescriptor;var S=Object.getOwnPropertyNames;var C=Object.prototype.hasOwnProperty;var I=(t,e)=>{for(var s in e)E(t,s,{get:e[s],enumerable:!0})},k=(t,e,s,n)=>{if(e&&typeof e=="object"||typeof e=="function")for(let r of S(e))!C.call(t,r)&&r!==s&&E(t,r,{get:()=>e[r],enumerable:!(n=O(e,r))||n.enumerable});return t};var b=t=>k(E({},"__esModule",{value:!0}),t);var x={};I(x,{handler:()=>J});module.exports=b(x);var m=require("@aws-sdk/client-sfn"),w=require("@aws-sdk/client-dynamodb"),a=require("@aws-sdk/lib-dynamodb"),p=require("@aws-sdk/client-eventbridge"),u=require("@aws-sdk/client-sns"),R=new m.SFNClient({}),l=a.DynamoDBDocumentClient.from(new w.DynamoDBClient({}),{marshallOptions:{removeUndefinedValues:!0}}),D=new p.EventBridgeClient({}),M=new u.SNSClient({}),f=process.env.TABLE_NAME,_=process.env.AUDIT_TABLE_NAME,T=process.env.PK_NAME||"pk",P=process.env.SK_NAME||"sk",g=process.env.NOTIFY_TOPIC_ARN;function o(t,e){return{statusCode:t,headers:{"content-type":"application/json","access-control-allow-origin":"*","access-control-allow-methods":"OPTIONS,POST","access-control-allow-headers":"*"},body:JSON.stringify(e)}}async function v(t,e){try{await D.send(new p.PutEventsCommand({Entries:[{Source:"stylingadventures.closet",DetailType:t,Detail:JSON.stringify(e)}]}))}catch(s){console.warn("[approve] EventBridge emit failed:",s)}}async function h(t,e,s){if(g)try{await M.send(new u.PublishCommand({TopicArn:g,Subject:t,Message:`${e}

${JSON.stringify(s,null,2)}`}))}catch(n){console.warn("[approve] SNS publish failed:",n)}}async function V(t,e,s){let n=new Date;await l.send(new a.PutCommand({TableName:_,Item:{pk:`APPROVAL#${e}`,sk:`TS#${n.toISOString()}`,action:t,approvalId:e,at:n.toISOString(),detail:s}}))}var J=async t=>{if(t?.requestContext?.http?.method==="OPTIONS")return o(200,{ok:!0});try{let e=typeof t.body=="string"?JSON.parse(t.body):t.body??{},{approvalId:s,decision:n}=e;if(!s||!n)return o(400,{message:"Missing approvalId or decision"});if(n!=="APPROVE"&&n!=="REJECT")return o(400,{message:"decision must be APPROVE or REJECT"});let r=`ITEM#${s}`,A="META",{Item:i}=await l.send(new a.GetCommand({TableName:f,Key:{[T]:r,[P]:A}}));if(!i)return o(404,{message:"Item not found"});if(i.status!=="PENDING")return o(200,{ok:!0,idempotent:!0,status:i.status});let y=i.taskToken;if(!y)return o(409,{message:"Missing taskToken (NotifyAdminFn not run yet)"});let c=e.reason??(n==="APPROVE"?"Approved by admin":"Rejected by admin");await R.send(new m.SendTaskSuccessCommand({taskToken:y,output:JSON.stringify({decision:n,reason:c})}));let d=new Date().toISOString(),N=n==="APPROVE"?"APPROVED":"REJECTED";return await l.send(new a.UpdateCommand({TableName:f,Key:{[T]:r,[P]:A},ConditionExpression:"#s = :pending",UpdateExpression:`
          SET #s = :s,
              decidedAt = :t,
              updatedAt = :t
          REMOVE taskToken, taskTokenExpiresAt
        `,ExpressionAttributeNames:{"#s":"status"},ExpressionAttributeValues:{":pending":"PENDING",":s":N,":t":d}})),await V(n==="APPROVE"?"ADMIN_APPROVE":"ADMIN_REJECT",s,{approvalId:s,decision:n,reason:c,decidedAt:d}),await v(n==="APPROVE"?"ClosetItemApproved":"ClosetItemRejected",{approvalId:s,decision:n,reason:c,decidedAt:d}),await h("Closet approval decision",`${n} for ${s}`,{approvalId:s,decision:n,reason:c,decidedAt:d}),o(200,{ok:!0,approvalId:s,status:N})}catch(e){return console.error("[approve] error:",e),e?.name==="ConditionalCheckFailedException"?o(200,{ok:!0,idempotent:!0}):o(500,{message:"Internal error"})}};0&&(module.exports={handler});
//# sourceMappingURL=index.js.map
