"use strict";var f=Object.defineProperty;var h=Object.getOwnPropertyDescriptor;var v=Object.getOwnPropertyNames;var M=Object.prototype.hasOwnProperty;var _=(e,t)=>{for(var s in t)f(e,s,{get:t[s],enumerable:!0})},b=(e,t,s,n)=>{if(t&&typeof t=="object"||typeof t=="function")for(let o of v(t))!M.call(e,o)&&o!==s&&f(e,o,{get:()=>t[o],enumerable:!(n=h(t,o))||n.enumerable});return e};var V=e=>b(f({},"__esModule",{value:!0}),e);var G={};_(G,{handler:()=>q});module.exports=V(G);var l=require("@aws-sdk/client-sfn"),R=require("@aws-sdk/client-dynamodb"),i=require("@aws-sdk/lib-dynamodb"),m=require("@aws-sdk/client-eventbridge"),E=require("@aws-sdk/client-sns"),x=new l.SFNClient({}),g=i.DynamoDBDocumentClient.from(new R.DynamoDBClient({}),{marshallOptions:{removeUndefinedValues:!0}}),J=new m.EventBridgeClient({}),U=new E.SNSClient({}),N=process.env.TABLE_NAME,B=process.env.AUDIT_TABLE_NAME,w=process.env.PK_NAME||"pk",P=process.env.SK_NAME||"sk",k=process.env.NOTIFY_TOPIC_ARN;function a(e,t){return{statusCode:e,headers:{"content-type":"application/json","access-control-allow-origin":"*","access-control-allow-methods":"OPTIONS,POST","access-control-allow-headers":"*"},body:JSON.stringify(t)}}function L(e){let t=e?.requestContext?.http?.method;if(t)return String(t).toUpperCase();let s=e?.requestContext?.httpMethod;if(s)return String(s).toUpperCase();let n=e?.httpMethod;if(n)return String(n).toUpperCase()}function F(e){if(typeof e!="string")return e??{};try{return JSON.parse(e)}catch{return{}}}function D(e){return e?.name==="ConditionalCheckFailedException"}function K(e){let t=String(e?.name||""),s=String(e?.message||"").toLowerCase();return t.includes("TaskTimedOut")||t.includes("InvalidToken")||t.includes("TaskDoesNotExist")||t.includes("ExecutionDoesNotExist")||s.includes("invalid token")||s.includes("task does not exist")||s.includes("timed out")}function I(e,t,s,n={}){console.log(JSON.stringify({_aws:{Timestamp:Date.now(),CloudWatchMetrics:[{Namespace:"StylingAdventures/ClosetApprovals",Dimensions:[Object.keys(n)],Metrics:[{Name:e,Unit:s}]}]},...n,[e]:t}))}async function $(e,t){try{await J.send(new m.PutEventsCommand({Entries:[{Source:"stylingadventures.closet",DetailType:e,Detail:JSON.stringify(t)}]}))}catch(s){console.warn("[approve] EventBridge emit failed:",s)}}async function j(e,t,s){if(k)try{await U.send(new E.PublishCommand({TopicArn:k,Subject:e,Message:`${t}

${JSON.stringify(s,null,2)}`}))}catch(n){console.warn("[approve] SNS publish failed:",n)}}async function A(e,t,s){let n=new Date;try{await g.send(new i.PutCommand({TableName:B,Item:{pk:`APPROVAL#${t}`,sk:`TS#${n.toISOString()}`,action:e,approvalId:t,at:n.toISOString(),detail:s}}))}catch(o){console.warn("[approve] audit write failed:",o)}}var q=async e=>{if(L(e)==="OPTIONS")return a(200,{ok:!0});try{let s=F(e?.body),n=s?.approvalId,o=s?.decision,c=s?.reason??(o==="APPROVE"?"Approved by admin":"Rejected by admin");if(!n||!o)return a(400,{message:"Missing approvalId or decision"});if(o!=="APPROVE"&&o!=="REJECT")return a(400,{message:"decision must be APPROVE or REJECT"});let y=`ITEM#${n}`,S="META",{Item:u}=await g.send(new i.GetCommand({TableName:N,Key:{[w]:y,[P]:S},ConsistentRead:!0}));if(!u)return a(404,{message:"Item not found"});if(u.status!=="PENDING")return a(200,{ok:!0,idempotent:!0,approvalId:n,status:u.status});let O=u.taskToken;if(!O)return a(409,{message:"Missing taskToken (NotifyAdminFn not run yet)"});let T=u.approvalRequestedAt;if(T){let r=Math.max(0,Math.floor((Date.now()-new Date(T).getTime())/1e3));I("ApprovalLatencySeconds",r,"Seconds",{Outcome:o==="APPROVE"?"APPROVED":"REJECTED"})}I("ApprovalCount",1,"Count",{Outcome:o==="APPROVE"?"APPROVED":"REJECTED"});let d=new Date().toISOString(),C=o==="APPROVE"?"APPROVED":"REJECTED",p=!0;try{await x.send(new l.SendTaskSuccessCommand({taskToken:O,output:JSON.stringify({decision:o,reason:c})}))}catch(r){p=!1,K(r)?(console.warn("[approve] task token already closed/invalid; continuing",{approvalId:n,err:r?.name||r}),await A("ADMIN_DECISION_TOKEN_CLOSED",n,{approvalId:n,decision:o,reason:c,at:d,error:String(r?.message||r)})):(console.error("[approve] SendTaskSuccess failed",r),await A("ADMIN_DECISION_SFN_ERROR",n,{approvalId:n,decision:o,reason:c,at:d,error:String(r?.message||r)}))}try{await g.send(new i.UpdateCommand({TableName:N,Key:{[w]:y,[P]:S},ConditionExpression:"#s = :pending",UpdateExpression:`
            SET #s = :s,
                decidedAt = :t,
                updatedAt = :t,
                decision = :d,
                decisionReason = :r
            REMOVE taskToken, taskTokenExpiresAt
          `,ExpressionAttributeNames:{"#s":"status"},ExpressionAttributeValues:{":pending":"PENDING",":s":C,":t":d,":d":o,":r":c}}))}catch(r){if(D(r))return a(200,{ok:!0,idempotent:!0,approvalId:n});throw r}return await A(o==="APPROVE"?"ADMIN_APPROVE":"ADMIN_REJECT",n,{approvalId:n,decision:o,reason:c,decidedAt:d,sfnOk:p}),await $(o==="APPROVE"?"ClosetItemApproved":"ClosetItemRejected",{approvalId:n,decision:o,reason:c,decidedAt:d,sfnOk:p}),await j("Closet approval decision",`${o} for ${n}`,{approvalId:n,decision:o,reason:c,decidedAt:d,sfnOk:p}),a(200,{ok:!0,approvalId:n,status:C,sfnOk:p})}catch(s){return console.error("[approve] error:",s),D(s)?a(200,{ok:!0,idempotent:!0}):a(500,{message:"Internal error"})}};0&&(module.exports={handler});
//# sourceMappingURL=index.js.map
