"use strict";var f=Object.defineProperty;var h=Object.getOwnPropertyDescriptor;var D=Object.getOwnPropertyNames;var v=Object.prototype.hasOwnProperty;var _=(e,t)=>{for(var s in t)f(e,s,{get:t[s],enumerable:!0})},M=(e,t,s,n)=>{if(t&&typeof t=="object"||typeof t=="function")for(let o of D(t))!v.call(e,o)&&o!==s&&f(e,o,{get:()=>t[o],enumerable:!(n=h(t,o))||n.enumerable});return e};var R=e=>M(f({},"__esModule",{value:!0}),e);var j={};_(j,{handler:()=>$});module.exports=R(j);var l=require("@aws-sdk/client-sfn"),P=require("@aws-sdk/client-dynamodb"),i=require("@aws-sdk/lib-dynamodb"),m=require("@aws-sdk/client-eventbridge"),E=require("@aws-sdk/client-sns"),b=new l.SFNClient({}),A=i.DynamoDBDocumentClient.from(new P.DynamoDBClient({}),{marshallOptions:{removeUndefinedValues:!0}}),x=new m.EventBridgeClient({}),V=new E.SNSClient({}),O=process.env.TABLE_NAME,J=process.env.AUDIT_TABLE_NAME,k=process.env.PK_NAME||"pk",w=process.env.SK_NAME||"sk",C=process.env.NOTIFY_TOPIC_ARN;function a(e,t){return{statusCode:e,headers:{"content-type":"application/json","access-control-allow-origin":"*","access-control-allow-methods":"OPTIONS,POST","access-control-allow-headers":"*"},body:JSON.stringify(t)}}function B(e){let t=e?.requestContext?.http?.method;if(t)return String(t).toUpperCase();let s=e?.requestContext?.httpMethod;if(s)return String(s).toUpperCase();let n=e?.httpMethod;if(n)return String(n).toUpperCase()}function U(e){if(typeof e!="string")return e??{};try{return JSON.parse(e)}catch{return{}}}function I(e){return e?.name==="ConditionalCheckFailedException"}function F(e){let t=String(e?.name||""),s=String(e?.message||"").toLowerCase();return t.includes("TaskTimedOut")||t.includes("InvalidToken")||t.includes("TaskDoesNotExist")||t.includes("ExecutionDoesNotExist")||s.includes("invalid token")||s.includes("task does not exist")||s.includes("timed out")}async function K(e,t){try{await x.send(new m.PutEventsCommand({Entries:[{Source:"stylingadventures.closet",DetailType:e,Detail:JSON.stringify(t)}]}))}catch(s){console.warn("[approve] EventBridge emit failed:",s)}}async function L(e,t,s){if(C)try{await V.send(new E.PublishCommand({TopicArn:C,Subject:e,Message:`${t}

${JSON.stringify(s,null,2)}`}))}catch(n){console.warn("[approve] SNS publish failed:",n)}}async function y(e,t,s){let n=new Date;try{await A.send(new i.PutCommand({TableName:J,Item:{pk:`APPROVAL#${t}`,sk:`TS#${n.toISOString()}`,action:e,approvalId:t,at:n.toISOString(),detail:s}}))}catch(o){console.warn("[approve] audit write failed:",o)}}var $=async e=>{if(B(e)==="OPTIONS")return a(200,{ok:!0});try{let s=U(e?.body),n=s?.approvalId,o=s?.decision,c=s?.reason??(o==="APPROVE"?"Approved by admin":"Rejected by admin");if(!n||!o)return a(400,{message:"Missing approvalId or decision"});if(o!=="APPROVE"&&o!=="REJECT")return a(400,{message:"decision must be APPROVE or REJECT"});let g=`ITEM#${n}`,N="META",{Item:p}=await A.send(new i.GetCommand({TableName:O,Key:{[k]:g,[w]:N}}));if(!p)return a(404,{message:"Item not found"});if(p.status!=="PENDING")return a(200,{ok:!0,idempotent:!0,approvalId:n,status:p.status});let S=p.taskToken;if(!S)return a(409,{message:"Missing taskToken (NotifyAdminFn not run yet)"});let d=new Date().toISOString(),T=o==="APPROVE"?"APPROVED":"REJECTED",u=!0;try{await b.send(new l.SendTaskSuccessCommand({taskToken:S,output:JSON.stringify({decision:o,reason:c})}))}catch(r){u=!1,F(r)?(console.warn("[approve] task token already closed/invalid; continuing",{approvalId:n,err:r?.name||r}),await y("ADMIN_DECISION_TOKEN_CLOSED",n,{approvalId:n,decision:o,reason:c,at:d,error:String(r?.message||r)})):(console.error("[approve] SendTaskSuccess failed",r),await y("ADMIN_DECISION_SFN_ERROR",n,{approvalId:n,decision:o,reason:c,at:d,error:String(r?.message||r)}))}try{await A.send(new i.UpdateCommand({TableName:O,Key:{[k]:g,[w]:N},ConditionExpression:"#s = :pending",UpdateExpression:`
            SET #s = :s,
                decidedAt = :t,
                updatedAt = :t
            REMOVE taskToken, taskTokenExpiresAt
          `,ExpressionAttributeNames:{"#s":"status"},ExpressionAttributeValues:{":pending":"PENDING",":s":T,":t":d}}))}catch(r){if(I(r))return a(200,{ok:!0,idempotent:!0,approvalId:n});throw r}return await y(o==="APPROVE"?"ADMIN_APPROVE":"ADMIN_REJECT",n,{approvalId:n,decision:o,reason:c,decidedAt:d,sfnOk:u}),await K(o==="APPROVE"?"ClosetItemApproved":"ClosetItemRejected",{approvalId:n,decision:o,reason:c,decidedAt:d,sfnOk:u}),await L("Closet approval decision",`${o} for ${n}`,{approvalId:n,decision:o,reason:c,decidedAt:d,sfnOk:u}),a(200,{ok:!0,approvalId:n,status:T,sfnOk:u})}catch(s){return console.error("[approve] error:",s),I(s)?a(200,{ok:!0,idempotent:!0}):a(500,{message:"Internal error"})}};0&&(module.exports={handler});
//# sourceMappingURL=index.js.map
